### ISSUE TITLE
Can' build multiple targets

### ISSUE THREAD

**Issue by lucabergamini** [galexite/bazel-cpp-tools#8]
The original repo has recently merged a change that allows building multiple targets at once (see [this PR](https://github.com/stackb/bazel-stack-vscode-cc/pull/13) and [the original issue](https://github.com/stackb/bazel-stack-vscode-cc/issues/11)).

The current status is that having multiple targets leads to an empty `json` file.

Would it be possible to piggyback that change also here? I can start a PR, but it's really a 1 line change so not sure it's worth it.

I've deployed it locally though (manually building the extension and installing in vscode) and I can confirm it works also for this repo.

**Comment by galexite** [comment]
Hi @lucabergamini! Thanks for bringing this to my attention! Yes, that would be a great idea, I'll commit it right away.

**Comment by galexite** [comment]
Done. Thanks once again!

**Comment by lucabergamini** [comment]
Are you also publishing a new release on the marketplace @galexite ?

**Comment by galexite** [comment]
I was hoping to improve a few rough edges for before my next release to the Marketplace but I've released v1.0.5 which includes this change. I hope to radically improve the extension (and my processes for building it before v1.1.0.

**Comment by lucabergamini** [comment]
> but I've released v1.0.5 which includes this change

Thanks a lot!. I'm actively using this extension, so reach out if you need someone to test additional features
